-- Create a temporary table for importing data
CREATE TEMPORARY TABLE heritage_sites_temp (
    ogc_fid INTEGER,
    geometry BYTEA,
    field1 BIGINT,
    folder_row BIGINT,
    cen BIGINT,
    yr BIGINT,
    sequence BIGINT,
    sec VARCHAR(254),
    rev BIGINT,
    type VARCHAR(254),
    type_desc VARCHAR(254),
    status_cod BIGINT,
    status VARCHAR(254),
    in_date DATE,
    listed DATE,
    designated DATE,
    easement_a VARCHAR(254),
    building_t VARCHAR(254),
    descriptio TEXT,
    bylaw_no VARCHAR(254),
    htg_conser VARCHAR(254),
    omb_date VARCHAR(254),
    reason VARCHAR(254),
    list_numbe VARCHAR(254),
    constructi VARCHAR(254),
    architect_ VARCHAR(254),
    year_demol VARCHAR(254),
    property_r BIGINT,
    property_s VARCHAR(254),
    property_y FLOAT,
    property_x FLOAT,
    house VARCHAR(254),
    prefix VARCHAR(254),
    street VARCHAR(254),
    type_1 VARCHAR(254),
    direction VARCHAR(254),
    unit_type VARCHAR(254),
    unit VARCHAR(254),
    city VARCHAR(254),
    province VARCHAR(254),
    postal_cod VARCHAR(254),
    address_ty VARCHAR(254),
    roll FLOAT,
    planning_d VARCHAR(254),
    former_mun VARCHAR(254),
    ward BIGINT,
    pre_dec_1_ BIGINT,
    address VARCHAR(254)
);

-- Import data from CSV or other source into heritage_sites_temp
-- COPY heritage_sites_temp FROM '/path/to/your/data.csv' WITH (FORMAT csv, HEADER true);

-- Transfer data from temporary table to main table
INSERT INTO heritage_sites (
    ogc_fid,
    geometry,
    field1,
    folder_row,
    cen,
    yr,
    sequence,
    sec,
    rev,
    type,
    type_desc,
    status_cod,
    status,
    in_date,
    listed,
    designated,
    easement_a,
    building_t,
    descriptio,
    bylaw_no,
    htg_conser,
    omb_date,
    reason,
    list_numbe,
    constructi,
    architect_,
    year_demol,
    property_r,
    property_s,
    property_y,
    property_x,
    house,
    prefix,
    street,
    type_1,
    direction,
    unit_type,
    unit,
    city,
    province,
    postal_cod,
    address_ty,
    roll,
    planning_d,
    former_mun,
    ward,
    pre_dec_1_,
    address
)
SELECT 
    ogc_fid,
    ST_GeomFromWKB(geometry::bytea, 4326),
    field1,
    folder_row,
    cen,
    yr,
    sequence,
    sec,
    rev,
    type,
    type_desc,
    status_cod,
    status,
    in_date,
    listed,
    designated,
    easement_a,
    building_t,
    descriptio,
    bylaw_no,
    htg_conser,
    omb_date,
    reason,
    list_numbe,
    constructi,
    architect_,
    year_demol,
    property_r,
    property_s,
    property_y,
    property_x,
    house,
    prefix,
    street,
    type_1,
    direction,
    unit_type,
    unit,
    city,
    province,
    postal_cod,
    address_ty,
    roll,
    planning_d,
    former_mun,
    ward,
    pre_dec_1_,
    address
FROM heritage_sites_temp;

-- Drop temporary table
DROP TABLE heritage_sites_temp; 